// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxnyjiwcojrdxvwwcwye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bnlqaXdjb2pyZHh2d3djd3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDE3ODYsImV4cCI6MjA2OTUxNzc4Nn0.bEafESY7Ydxy-kRFKmB1sFN88QhtVHPZK311NB1pDjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});